name: Copy Sanity Production Dataset
on:
  push:
    branches:
      # only run on feature branches, excluding production and staging just to be safe
      - "feature/**"
      - "!production"
      - "!main"
      - "!staging"
jobs:
  copy-dataset:
    runs-on: ubuntu-latest
    name: Export production dataset and import to staging
    steps:
      - name: Double-check branch name
        # branch "feature/production" would trigger this action
        # so we will cancel the job if that happens
        run: |
          if [ ${GITHUB_REF##*/} = "production" ]; then exit 1; fi
          if [ ${GITHUB_REF##*/} = "main" ]; then exit 1; fi
      - name: Export dataset from production
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_EXPORT_DATASET }}
        with:
          args: dataset export production exports/production.tar.gz
      - name: Upload production.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: export-tarball
          path: exports/production.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
      - name: Import dataset to staging
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_IMPORT_DATASET }}
        with:
          args: dataset import exports/production.tar.gz staging --replace
